language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
env:
  matrix:
  - secure: gXNZa645VKuxHAVCTxUIvLsPsLkRtEwKvlfaUYZf5owqNKWf5M5cOsZC4FDImn3Da1bwal7Hoxe+go+ed6EuUVY/K/mcBxieeQVeAT5IvM0kCZ10g5n4AF4zM2IJIWHVIyJoN3ExOjkbrJr8EeBgE4Wue1oDOK1NlBDz8Hu9n44=
  - secure: RGYpAW2tvzsbrHhEFm+focI6vzcKjO9d4/lbn/1JNURwYYthxTFM2OgFBYGFoyokYoIFskJjJdnRujehZHm+XluULf08iOgQAfD6euZA/23pS7jh9bZIkVMrKzm1Or7JmrHlbWP8JyMbNPs7WQzicVgTnvaFRy9ZEm0D3MQ+aZg=
