language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
env:
  global:
  - secure: LmEVfLdKCdPbtA4xObeZgw4pM8Gl+Gdrr86NDyh7KxTyVW/zpbuf9uN0xzZw0eaN2FcK8k1Hl38HPCfIVMDLEzgAvTdOTQozRpE6NrIrxVw7+y+YkXKMoHAEHGuZsJNTZzx4SEc77Cx+pIzsU979MWIk1ZptGnvGog9Z/YEtMpg=
  - secure: JwwG2zBiW9Y/SnD5t1mIAdTJHyejQL63HISl/NwElkiN4rhd4Rcuur0dydEX3WPo+p6/VVA7W3+Fo8EH7DvGPk7Z5bKCdQahI+FydKET/jURM41ec3XbPMjm7gXZywCdyLHN68teO0cvVYGbh9SEmKEIgElPSsZU7FxxG77oXec=
